//
// Syslog_ServiceRegistration.mof
//
// Copyright (c) IBM Corp. 2003, 2009
//
// THIS FILE IS PROVIDED UNDER THE TERMS OF THE ECLIPSE PUBLIC LICENSE
// ("AGREEMENT"). ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS FILE
// CONSTITUTES RECIPIENTS ACCEPTANCE OF THE AGREEMENT.
//
// You can obtain a current copy of the Eclipse Public License from
// http://www.opensource.org/licenses/eclipse-1.0.php
//
// Author: R Sharada <sharada@in.ibm.com>
//
// Interface Type: Common Manageability Programming Interface ( CMPI )
//
// Description: CIM Classes for Linux Syslog Service Instrumentation 
// ( This is used for registration of classes in Pegasus )
//


#pragma locale ("en_US")
#pragma namespace ("root/PG_InterOp")

// Syslog_Service 

instance of PG_ProviderModule
{
   Name = "Syslog_ServiceProviderModule";
   //The library name on disk
   Location = "Syslog_Service";
   Vendor = "SBLIM";
   Version = "2.0.0";
   InterfaceType = "CMPI";
   InterfaceVersion = "2.0.0";
};

instance of PG_Provider
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "Syslog_ServiceProviderModule";
   // The provider name as referenced in the code
   Name = "Syslog_Service";
};

instance of PG_ProviderCapabilities
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "Syslog_ServiceProviderModule";
   //The provider name as defined in PG_Provider
   ProviderName = "Syslog_Service";
   CapabilityID = "1";
   //Name of the CIM class as defined in the mof
   ClassName = "Syslog_Service";
   Namespaces = {"root/cimv2"};
   ProviderType = { 2,5 }; // Instance, Method
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};

// Syslog_ServiceProcess 

instance of PG_ProviderModule
{
   Name = "Syslog_ServiceProcessProviderModule";
   //The library name on disk
   Location = "Syslog_ServiceProcess";
   Vendor = "SBLIM";
   Version = "2.0.0";
   InterfaceType = "CMPI";
   InterfaceVersion = "2.0.0";
};

instance of PG_Provider
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "Syslog_ServiceProcessProviderModule";
   // The provider name as referenced in the code
   Name = "Syslog_ServiceProcess";
};

instance of PG_ProviderCapabilities
{
   //The provider module as defined in PG_ProviderModule
   ProviderModuleName = "Syslog_ServiceProcessProviderModule";
   //The provider name as defined in PG_Provider
   ProviderName = "Syslog_ServiceProcess";
   CapabilityID = "1";
   //Name of the CIM class as defined in the mof
   ClassName = "Syslog_ServiceProcess";
   Namespaces = {"root/cimv2"};
   ProviderType = { 3 }; // Assoc
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};



